version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    target-branch: "5.2.x"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/"
    target-branch: "5.1.x"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/"
    target-branch: "5.0.x"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/"
    target-branch: "4.7.x"
    schedule:
      interval: "daily"

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
