dist: trusty
language: java
jdk:
  - oraclejdk8
cache:
  directories:
  - $HOME/.m2

install: ./mvnw -B clean validate

script:
  - ./mvnw -B -Pcheck-duplicate,check-checkstyle,check-cycles,check-cpd,check-pmd,check-findbugs -DskipTests=true install
  - ./mvnw -B verify

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - "[[ ${TRAVIS_PULL_REQUEST} == 'false' ]] && ./mvnw -B org.eluder.coveralls:coveralls-maven-plugin:4.3.0:report"
